// Function Factory basics: what a function is and why we use one, then writing your own.
export const functionBasics = [
  {
    id: "fg-1",
    title: { en: "Press the Recipe", zh: "按下食譜" },
    story: {
      en: "A function is like a recipe card. \"hop\" is already written: it moves 2 squares. Put ONE \"hop\" under ▶ when Run and watch what it does.",
      zh: "函式就像一張食譜卡。「跳兩格」已經寫好了：它會前進 2 格。在「▶ 按下執行時」下面放「一個」跳兩格，看看它做了什麼。",
    },
    hint: { en: "Writing the recipe is not enough. You have to USE it under ▶ Run.", zh: "只寫食譜不會做菜，要把它放到「▶ 按下執行時」下面才會用到。" },
    maps: [[">.G"]],
    blocks: ["move", "def", "call"],
    functions: ["hop"],
    require: { call: 1 },
    starter: { main: [], defs: { hop: ["move", "move"] } },
    solution: { main: [{ call: "hop" }], defs: { hop: ["move", "move"] } },
  },
  {
    id: "fg-13",
    title: { en: "Pick the Right Recipe", zh: "挑對的食譜" },
    story: {
      en: "There are two recipes now: \"hop\" moves 2 squares and \"dash\" moves 3. The flag is 5 squares away. Which ones do you need?",
      zh: "現在有兩張食譜：「跳兩格」走 2 格、「衝三格」走 3 格。旗子在 5 格外，要用哪幾個？",
    },
    hint: { en: "2 + 3 = 5. Using the wrong one makes Robo hit the wall, so press Run and look!", zh: "2 + 3 = 5。用錯的話 Robo 會撞牆，按執行看看就知道！" },
    maps: [[">....G"]],
    blocks: ["move", "def", "call"],
    functions: ["hop", "dash"],
    require: { call: 2 },
    maxBlocks: 9,
    starter: { main: [], defs: { hop: ["move", "move"], dash: ["move", "move", "move"] } },
    solution: { main: [{ call: "hop" }, { call: "dash" }], defs: { hop: ["move", "move"], dash: ["move", "move", "move"] } },
  },
  {
    id: "fg-2",
    title: { en: "Too Many Blocks", zh: "方塊太多了" },
    story: {
      en: "This program works, but it uses too many blocks! \"dash\" moves 3 squares. Replace the 6 move blocks with dash.",
      zh: "這個程式走得到，但方塊太多了！「衝三格」會前進 3 格。用衝三格換掉 6 個前進方塊。",
    },
    hint: { en: "6 squares = dash + dash.", zh: "6 格 = 衝三格 + 衝三格。" },
    maps: [[">......G"]],
    blocks: ["move", "def", "call"],
    functions: ["dash"],
    require: { call: 2 },
    starter: { main: ["move", "move", "move", "move", "move", "move", "move"], defs: { dash: ["move", "move", "move"] } },
    solution: { main: [{ call: "dash" }, { call: "dash" }, "move"], defs: { dash: ["move", "move", "move"] } },
  },
  {
    id: "fg-3",
    title: { en: "Fix Once, Fixed Everywhere", zh: "改一次，全部都好" },
    story: {
      en: "The main program uses \"dash\" 3 times, but dash only moves 2 squares. Don't touch the main program: fix dash itself!",
      zh: "主程式用了 3 次「衝三格」，可是衝三格只走 2 格。不要動主程式，直接修好衝三格！",
    },
    hint: { en: "Add one more move inside the purple define block.", zh: "在紫色的「定義」方塊裡多加一個前進。" },
    maps: [[">.........G"]],
    blocks: ["move", "def", "call"],
    functions: ["dash"],
    require: { call: 3 },
    starter: { main: [{ call: "dash" }, { call: "dash" }, { call: "dash" }, "move"], defs: { dash: ["move", "move"] } },
    solution: { main: [{ call: "dash" }, { call: "dash" }, { call: "dash" }, "move"], defs: { dash: ["move", "move", "move"] } },
  },
  {
    id: "fg-4",
    title: { en: "Dash Around the Corner", zh: "衝過轉角" },
    story: {
      en: "Use \"dash\" to go right, turn, then dash again to reach the flag.",
      zh: "用「衝三格」往右衝，轉個彎，再衝一次到旗子。",
    },
    hint: { en: "dash, turn left, dash.", zh: "衝三格、左轉、衝三格。" },
    maps: [["   G", "   .", "   .", ">..."]],
    blocks: ["move", "left", "right", "def", "call"],
    functions: ["dash"],
    require: { call: 2 },
    starter: { main: [], defs: { dash: ["move", "move", "move"] } },
    solution: { main: [{ call: "dash" }, "left", { call: "dash" }], defs: { dash: ["move", "move", "move"] } },
  },
  {
    id: "fg-5",
    title: { en: "Write Your Own Recipe", zh: "自己寫食譜" },
    story: {
      en: "Now YOU write the function. Make \"grab\" walk 2 squares and pick up the gem. Then use it 3 times.",
      zh: "這次換你寫函式。讓「走走撿」走 2 格再撿起寶石，然後用它 3 次。",
    },
    hint: { en: "grab = move, move, pick up.", zh: "走走撿 = 前進、前進、撿起。" },
    maps: [[">.*.*.*G"]],
    blocks: ["move", "pick", "def", "call"],
    functions: ["grab"],
    require: { call: 3 },
    starter: { main: [], defs: { grab: [] } },
    solution: { main: [{ call: "grab" }, { call: "grab" }, { call: "grab" }, "move"], defs: { grab: ["move", "move", "pick"] } },
  },
  {
    id: "fg-7",
    title: { en: "Repeat the Function", zh: "重複使用函式" },
    story: {
      en: "Every stair has a gem. Make \"gem step\" for ONE stair, then put it inside a repeat.",
      zh: "每一階樓梯都有寶石。做一個「階梯撿寶」代表「一階」，再把它放進重複裡。",
    },
    hint: { en: "gem step: move, pick up, turn left, move, turn right.", zh: "階梯撿寶：前進、撿起、左轉、前進、右轉。" },
    maps: [["####.G", "###.*#", "##.*##", "#.*###", ">*####"]],
    blocks: ["move", "left", "right", "pick", "repeat", "def", "call"],
    functions: ["gemStep"],
    require: { call: 1, repeat: 1 },
    starter: { main: [], defs: { gemStep: [] } },
    solution: {
      main: [{ repeat: 4, do: [{ call: "gemStep" }] }, "move"],
      defs: { gemStep: ["move", "pick", "left", "move", "right"] },
    },
  },
  {
    id: "fg-8",
    title: { en: "Two Helpers", zh: "兩個小幫手" },
    story: {
      en: "Gems hide in pockets above AND below the road. Make one function for each kind of pocket.",
      zh: "寶石藏在路的上方和下方的小口袋裡。上面一種、下面一種，各做一個函式。",
    },
    hint: {
      en: "up pocket: left, move, pick up, right, right, move, left. down pocket is the mirror: swap left and right.",
      zh: "上口袋：左轉、前進、撿起、右轉、右轉、前進、左轉。下口袋左右相反。",
    },
    maps: [["#*##*#", ">....G", "###*##"]],
    blocks: ["move", "left", "right", "pick", "def", "call"],
    functions: ["pocketUp", "pocketDown"],
    require: { def: 2, call: 3 },
    starter: { main: [], defs: { pocketUp: [], pocketDown: [] } },
    solution: {
      main: ["move", { call: "pocketUp" }, "move", "move", { call: "pocketDown" }, "move", { call: "pocketUp" }, "move"],
      defs: {
        pocketUp: ["left", "move", "pick", "right", "right", "move", "left"],
        pocketDown: ["right", "move", "pick", "left", "left", "move", "right"],
      },
    },
  },
];
