// Advanced Unit 4 · Lists: one box that holds many numbers in order. Loop over it, add to it, search it.
const set = (v, value) => ({ op: "setVar", var: v, value });
const add = (v, value = 1) => ({ op: "changeVar", var: v, value });
const say = (v) => ({ op: "sayVar", var: v });
const forEach = (body) => ({ op: "forEach", do: body });
const push = (value) => ({ op: "addList", value });
const ifCmp = (v, cmp, value, body) => ({ op: "ifCmp", var: v, cmp, value, do: body });
const WALK = { go: [{ repeatN: true, do: ["move"] }] };
const ROW = { row: [{ repeatN: true, do: ["move", "pick"] }] };
const SPIRAL = [">....", "#..G.", "#.##.", "#...."];
const ROWS_A = [">**#", "##.#", "G**#"];
const ROWS_B = [">.*.", "G##*", "****"];
// Walk a spiral; at each corner add this row's gems to the list. The last row has no corner, so add it after the loop.
const gemsPerRow = [
  set("gems", 0),
  { until: true, do: [{ if: "pathAhead", do: ["move", { if: "gemHere", do: ["pick", add("gems")] }],
    else: [push("gems"), set("gems", 0), "right"] }] },
  push("gems"),
];
const biggest = [set("best", 0), forEach([ifCmp("item", "gt", "best", [set("best", "item")])])];

export const lists = [
  {
    id: "ls-1",
    title: { en: "One Step per Item", zh: "一個項目走一步" },
    story: {
      en: "A list 📦 is one box that holds many numbers in order. \"for each item\" runs once for EVERY number in the list. How far does Robo go?",
      zh: "串列 📦 是一個依照順序裝很多數字的盒子。「對串列裡的每個項目」會對「每一個」數字各做一次。Robo 會走多遠？",
    },
    hint: { en: "for each item → move. 5 items = 5 moves.", zh: "對每個項目 → 前進。5 個項目 = 前進 5 次。" },
    maps: [[">....G"], [">..G"]],
    lists: [[5, 2, 9, 1, 7], [8, 3, 6]],
    blocks: ["move", "forEach"],
    require: { forEach: 1 },
    maxBlocks: 3,
    starter: { main: [] },
    solution: { main: [forEach(["move"])] },
  },
  {
    id: "ls-2",
    title: { en: "Follow the List", zh: "照著串列走" },
    story: {
      en: "The list tells Robo how long each straight part is. For each item: walk with 🎛️ 📦 item, then turn right.",
      zh: "串列告訴 Robo 每一段直線有多長。對每個項目：走 輸入 🎛️ 📦 項目，然後右轉。",
    },
    hint: { en: "for each item (walk with 📦 item, turn right).", zh: "對每個項目（走 輸入 📦 項目、右轉）。" },
    maps: [SPIRAL, [">..#", "##.#", "##.#", "##G#"]],
    lists: [[4, 3, 3, 2, 2], [2, 3]],
    blocks: ["move", "right", "forEach", "def", "callN", "repeatN"],
    functions: ["go"],
    tokens: ["item"],
    require: { forEach: 1 },
    starter: { main: [], defs: WALK },
    solution: { main: [forEach([{ call: "go", n: "item" }, "right"])], defs: WALK },
  },
  {
    id: "ls-3",
    title: { en: "Add Up the List", zh: "把串列加起來" },
    story: {
      en: "The list has the price of each snack. Walk to the flag and say the 🧮 total: change total by 📦 item for each item.",
      zh: "串列裡是每樣點心的價錢。走到旗子，說出 🧮 總和：對每個項目，總和改變 📦 項目。",
    },
    hint: { en: "Set 🧮 total to 0 → for each item (change 🧮 total by + 📦 item) → say 🧮 total.", zh: "🧮 總和設為 0 → 對每個項目（🧮 總和改變 + 📦 項目）→ 說出 🧮 總和。" },
    maps: [[">G"], [">G"]],
    lists: [[3, 1, 4], [2, 5, 2, 1]],
    blocks: ["move", "forEach", "setVar", "changeVar", "sayVar"],
    vars: ["total"],
    tokens: ["item"],
    expect: "wants",
    wants: [8, 10],
    starter: { main: ["move"] },
    solution: { main: ["move", set("total", 0), forEach([add("total", "item")]), say("total")] },
  },
  {
    id: "ls-4",
    title: { en: "Count the Big Ones", zh: "數大的數字" },
    story: {
      en: "How many numbers in the list are bigger than 3? For each item, compare it with 3.",
      zh: "串列裡有幾個數字比 3 大？對每個項目，把它和 3 比較。",
    },
    hint: { en: "for each item: if 📦 item > 3 → 🔢 +1. Then say.", zh: "對每個項目：如果 📦 項目 > 3 → 🔢 +1。最後說出。" },
    maps: [[">G"], [">G"]],
    lists: [[5, 2, 9, 3, 4], [1, 7, 2]],
    blocks: ["move", "forEach", "setVar", "changeVar", "sayVar", "ifCmp"],
    vars: ["counter"],
    tokens: ["item"],
    expect: "wants",
    wants: [3, 1],
    starter: { main: ["move", set("counter", 0), forEach([add("counter")]), say("counter")] },
    solution: { main: ["move", set("counter", 0), forEach([ifCmp("item", "gt", 3, [add("counter")])]), say("counter")] },
  },
  {
    id: "ls-5",
    title: { en: "Make a List", zh: "做一個串列" },
    story: {
      en: "The list starts empty. Every time Robo finds a gem, add 👣 steps to the list, so we know WHERE each gem was. Say the list at the flag.",
      zh: "串列一開始是空的。Robo 每找到一顆寶石，就把 👣 步數加進串列，這樣就知道每顆寶石在「哪裡」。到旗子時說出串列。",
    },
    hint: { en: "Repeat until 🏁: move, 👣 +1, if on a gem → (pick up, add 👣 steps to the list). Then say the list.", zh: "重複直到 🏁：前進、👣 +1、站在寶石上 →（撿起、把 👣 步數加進串列）。最後說出串列。" },
    maps: [[">*.**.G"], [">..*.*G"]],
    blocks: ["move", "pick", "until", "if", "setVar", "changeVar", "addList", "sayList"],
    vars: ["steps"],
    expect: "wants",
    wants: [[1, 3, 4], [3, 5]],
    starter: { main: [set("steps", 0), { until: true, do: ["move", add("steps"), { if: "gemHere", do: ["pick"] }] }, "sayList"] },
    solution: { main: [set("steps", 0), { until: true, do: ["move", add("steps"), { if: "gemHere", do: ["pick", push("steps")] }] }, "sayList"] },
  },
  {
    id: "ls-6",
    title: { en: "Don't Forget the Last One", zh: "別忘了最後一個" },
    story: {
      en: "At each corner, Robo adds that row's 💎 gems to the list. But the last row has no corner, so it is missing! Add it after the loop.",
      zh: "每到轉角，Robo 就把這一排的 💎 寶石數加進串列。可是最後一排沒有轉角，所以少了一個！在迴圈後面把它加進去。",
    },
    hint: { en: "After the loop, before saying: add 💎 gems to the list.", zh: "迴圈結束後、說出之前：把 💎 寶石數加進串列。" },
    maps: [ROWS_A, ROWS_B],
    blocks: ["move", "right", "pick", "until", "if", "ifElse", "setVar", "changeVar", "addList", "sayList"],
    vars: ["gems"],
    expect: "wants",
    wants: [[2, 1, 1], [1, 2, 3, 0]],
    starter: { main: [...gemsPerRow.slice(0, -1), "sayList"] },
    solution: { main: [...gemsPerRow, "sayList"] },
  },
  {
    id: "ls-7",
    title: { en: "The Biggest Number", zh: "最大的數字" },
    story: {
      en: "Find the biggest number in the list. Keep 🏆 biggest: for each item, if 📦 item > 🏆 biggest, copy the item into biggest.",
      zh: "找出串列裡最大的數字。用 🏆 最大值記住它：對每個項目，如果 📦 項目 > 🏆 最大值，就把項目複製到最大值。",
    },
    hint: { en: "Set 🏆 to 0 → for each item (if 📦 item > 🏆 → set 🏆 to 📦 item) → say 🏆.", zh: "🏆 設為 0 → 對每個項目（如果 📦 項目 > 🏆 → 🏆 設為 📦 項目）→ 說出 🏆。" },
    maps: [[">G"], [">G"]],
    lists: [[3, 8, 2, 6], [9, 4, 7]],
    blocks: ["move", "forEach", "setVar", "sayVar", "ifCmp"],
    vars: ["best"],
    tokens: ["item"],
    expect: "wants",
    wants: [8, 9],
    starter: { main: ["move"] },
    solution: { main: ["move", ...biggest, say("best")] },
  },
  {
    id: "ls-8",
    title: { en: "Rows From a List", zh: "照串列撿寶石" },
    story: {
      en: "No flag today: collect all 7 gems. Each number tells how many gems are in that row. For each item: gem row with 🎛️ 📦 item, then turn right.",
      zh: "今天沒有旗子：把 7 顆寶石全部撿起來。每個數字代表那一排有幾顆寶石。對每個項目：寶石列 輸入 🎛️ 📦 項目，然後右轉。",
    },
    hint: { en: "gem row: repeat input times (move, pick up). Main: for each item (gem row with 📦 item, turn right).", zh: "寶石列：重複 輸入 次（前進、撿起）。主程式：對每個項目（寶石列 輸入 📦 項目、右轉）。" },
    maps: [[">***", "###*", "#***"], [">**", "##*", "##*", "***"]],
    lists: [[3, 2, 2], [2, 3, 2]],
    win: { goal: false, exactGems: 7 },
    blocks: ["move", "right", "pick", "forEach", "def", "callN", "repeatN"],
    functions: ["row"],
    tokens: ["item"],
    starter: { main: [], defs: { row: [] } },
    solution: { main: [forEach([{ call: "row", n: "item" }, "right"])], defs: ROW },
  },
  {
    id: "ls-9",
    title: { en: "Build a Countdown", zh: "做一個倒數串列" },
    story: {
      en: "A loop can build a list! Start 🔢 counter at 5. Add the counter to the list and take 1 away, until it reaches 0. Say the list.",
      zh: "迴圈可以做出串列！🔢 計數器從 5 開始。把計數器加進串列、再減 1，直到變成 0。說出串列。",
    },
    hint: { en: "Set 🔢 to 5 → repeat until 🔢 = 0 (add 🔢 to the list, 🔢 -1) → say the list.", zh: "🔢 設為 5 → 重複直到 🔢 = 0（把 🔢 加進串列、🔢 -1）→ 說出串列。" },
    maps: [[">G"]],
    blocks: ["move", "setVar", "changeVar", "untilCmp", "addList", "sayList"],
    vars: ["counter"],
    expect: "wants",
    wants: [[5, 4, 3, 2, 1]],
    starter: { main: ["move", set("counter", 5), "sayList"] },
    solution: { main: ["move", set("counter", 5), { op: "untilCmp", var: "counter", cmp: "eq", value: 0, do: [push("counter"), add("counter", -1)] }, "sayList"] },
  },
  {
    id: "ls-10",
    title: { en: "Is There a 7?", zh: "裡面有 7 嗎？" },
    story: {
      en: "Search the list! 🔍 found starts at 0 (no). If any item = 7, set found to 1 (yes). Say found.",
      zh: "在串列裡找一找！🔍 找到了 一開始是 0（沒有）。如果有項目 = 7，就把它設為 1（有）。說出 🔍 找到了。",
    },
    hint: { en: "Set 🔍 to 0 → for each item (if 📦 item = 7 → set 🔍 to 1) → say 🔍.", zh: "🔍 設為 0 → 對每個項目（如果 📦 項目 = 7 → 🔍 設為 1）→ 說出 🔍。" },
    maps: [[">G"], [">G"], [">G"]],
    lists: [[3, 7, 2], [4, 1, 5, 9], [7]],
    blocks: ["move", "forEach", "setVar", "sayVar", "ifCmp"],
    vars: ["found"],
    tokens: ["item"],
    expect: "wants",
    wants: [1, 0, 1],
    starter: { main: ["move", set("found", 1), say("found")] },
    solution: { main: ["move", set("found", 0), forEach([ifCmp("item", "eq", 7, [set("found", 1)])]), say("found")] },
  },
  {
    id: "ls-11",
    title: { en: "Which Room Wins?", zh: "哪一間贏了？" },
    story: {
      en: "Each number is how many gems a room has. Say the POSITION of the biggest room (1st, 2nd, 3rd…), not the number itself.",
      zh: "每個數字是一間房間的寶石數。說出寶石最多的房間是「第幾間」（第 1、2、3……），不是寶石數。",
    },
    hint: { en: "For each item: 🔢 +1 first. If 📦 item > 🏆 → set 🏆 to item AND set 📍 position to 🔢.", zh: "對每個項目：先 🔢 +1。如果 📦 項目 > 🏆 → 🏆 設為項目，「而且」📍 位置設為 🔢。" },
    maps: [[">G"], [">G"]],
    lists: [[3, 8, 2, 6], [2, 4, 9]],
    blocks: ["move", "forEach", "setVar", "changeVar", "sayVar", "ifCmp"],
    vars: ["counter", "best", "where"],
    tokens: ["item"],
    expect: "wants",
    wants: [2, 3],
    starter: { main: ["move", ...biggest, say("best")] },
    solution: {
      main: ["move", set("counter", 0), set("best", 0),
        forEach([add("counter"), ifCmp("item", "gt", "best", [set("best", "item"), set("where", "counter")])]), say("where")],
    },
  },
  {
    id: "ls-12",
    title: { en: "Treasure Survey", zh: "寶藏調查" },
    story: {
      en: "Boss mission! Walk each spiral and build a list of gems per row. Then go through your list and say the biggest row.",
      zh: "魔王關！走完每個漩渦，做出每一排寶石數的串列。然後檢查你的串列，說出最多的一排。",
    },
    hint: { en: "First: \"Don't Forget the Last One\". Then: \"The Biggest Number\" using your own list.", zh: "先做「別忘了最後一個」，再用你自己的串列做「最大的數字」。" },
    maps: [ROWS_A, ROWS_B, [">*.**", "    *", " .G *", " *.*."]],
    blocks: ["move", "right", "pick", "until", "if", "ifElse", "forEach", "setVar", "changeVar", "sayVar", "ifCmp", "addList"],
    vars: ["gems", "best"],
    tokens: ["item"],
    expect: "wants",
    wants: [2, 3, 3],
    starter: { main: [] },
    solution: { main: [...gemsPerRow, ...biggest, say("best")] },
  },
];

export const LISTS_PATH = [
  ["ls-1", "easy", { en: "A list holds many numbers; \"for each\" runs once per item.", zh: "串列裝很多數字；「對每個項目」每個數字做一次。" }],
  ["ls-2", "easy", { en: "Use each item as a function input.", zh: "把每個項目當作函式的輸入。" }],
  ["ls-3", "easy", { en: "Add up every item in a list.", zh: "把串列裡每個項目加起來。" }],
  ["ls-4", "easy", { en: "Compare each item to count only some of them.", zh: "比較每個項目，只數其中一些。" }],
  ["ls-5", "medium", { en: "Add to a list to remember many things.", zh: "把東西加進串列，就能記住很多個。" }],
  ["ls-6", "medium", { en: "Check the end: the last one is easy to forget.", zh: "檢查結尾：最後一個最容易忘記。" }],
  ["ls-7", "medium", { en: "Find the biggest item in a list.", zh: "找出串列裡最大的項目。" }],
  ["ls-8", "medium", { en: "A list can drive a function.", zh: "串列可以帶著函式做事。" }],
  ["ls-9", "hard", { en: "A loop can build a list.", zh: "迴圈可以做出一個串列。" }],
  ["ls-10", "hard", { en: "Search a list: use a 0/1 box for yes or no.", zh: "在串列裡搜尋：用 0／1 盒子表示有沒有。" }],
  ["ls-11", "hard", { en: "Keep track of WHERE, not just WHAT.", zh: "記住「在哪裡」，不只是「是什麼」。" }],
  ["ls-12", "hard", { en: "Use everything together.", zh: "全部學到的一起用。" }],
];
